version: '3'
services:
  reactjsapp:
    build: ../reactApp
    image: "reactjs:1.0"
    networks:
      - react-nginx-net
  revproxy:
    build: ../reverseproxy
    image: "reverseproxy:1.0"
    networks:
      - react-nginx-net
    ports:
      - "8000:80"
networks:
  react-nginx-net:
  
  
  